// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkhnzkuxktjoxjvmkart.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpraG56a3V4a3Rqb3hqdm1rYXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5ODA1MjEsImV4cCI6MjA1NTU1NjUyMX0.ziMthGIwOO7KJgHYgU3rY_5eVkVgMl6ICEEAbBcClpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);